### ISSUE TITLE
Project maintainer

### ISSUE THREAD

**Issue by tmcgilchrist** [statusfailed/snaplet-riak#2]
Hi, 

I'm the current maintainer of the riak-haskell-client package and found this project linked off hackage as a dependency. If the comment in the README is correct I'd like to see if you're still interested in offloading the maintainership of this package. 

As a minimum I'd like to update it to a recent version of riak, update the various deps like lens and generally ensure it works as described for snap.

Cheers

**Comment by statusfailed** [comment]
Whoops! Sorry, only just saw this message. I would be more than happy to transfer ownership of this package - what's the best way to do that?

**Comment by tmcgilchrist** [comment]
Heh, no worries. I think adding me as a maintainer on hackage would be sufficient, if that's cool (lambda_foo / https://hackage.haskell.org/user/lambda_foo). I can then upload new versions etc.

What do you think about switching the official git repo to my fork?

**Comment by statusfailed** [comment]
Sounds good - I've had to email the hackage admin to reset my account
though - I haven't logged in for a while. Switching the official repo
sounds like a good idea too - much less confusing to have it under the
maintainer's name!

Will let you know once I get my account back heh

**Comment by statusfailed** [comment]
Sorry about the delay- I've added you to the maintainers list. I think you
should be able to change the official repo now - let me know if that's all
OK!

**Comment by tmcgilchrist** [comment]
Looks ok, cheers. I'll prep an updated version of the package that supports the latest Riak driver when I have a chance this week.
